package cli

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strings"

	"github.com/hashload/boss/pkg/msg"
	"github.com/spf13/cobra"
)

const (
	// securityPolicyFile is the security disclosure policy generated by 'cra init'.
	securityPolicyFile = "SECURITY.md"
	// sbomBaseName is the base name passed to the SBOM generator; the generator
	// appends the format extension.
	sbomBaseName = "sbom"
	// sbomFileName is the resulting CycloneDX file that 'cra' looks for.
	sbomFileName = sbomBaseName + ".cdx.json"
)

var securityEmail string

// craCmdRegister registers the cra commands under the boss CLI root.
func craCmdRegister(root *cobra.Command) {
	var craCmd = &cobra.Command{
		Use:   "cra",
		Short: "Cyber Resilience Act (CRA) compliance checker and assistant",
		Long: `Diagnose and automate Cyber Resilience Act (CRA) compliance for your Delphi project.
Run without arguments to perform a local compliance check, or use 'cra init' to generate required files.`,
		Run: func(cmd *cobra.Command, _ []string) {
			runCraCheck()
		},
	}

	var initCmd = &cobra.Command{
		Use:   "init",
		Short: "Start interactive wizard to make your project 100% CRA compliant",
		Long:  "Start the interactive wizard to generate required Cyber Resilience Act (CRA) compliance files, such as SECURITY.md and sbom.cdx.json.",
		Run: func(cmd *cobra.Command, _ []string) {
			runCraInit()
		},
	}

	initCmd.Flags().StringVar(&securityEmail, "email", "", "Security contact email for reporting vulnerabilities")

	craCmd.AddCommand(initCmd)
	root.AddCommand(craCmd)
}

// runCraCheck performs a local diagnostic of the project against CRA/Portal signals.
func runCraCheck() {
	msg.Info("🔍 Diagnosing Cyber Resilience Act (CRA) Compliance...\n")

	hasSecurity := false
	securityCandidates := []string{securityPolicyFile, ".github/" + securityPolicyFile, "docs/" + securityPolicyFile}
	for _, c := range securityCandidates {
		if _, err := os.Stat(c); err == nil {
			hasSecurity = true
			msg.Info("✅ Security Policy: Found security disclosure policy at '%s'", c)
			break
		}
	}
	if !hasSecurity {
		msg.Warn("❌ Security Policy: Missing 'SECURITY.md' in the repository.")
		msg.Info("   -> To fix: Run 'boss cra init' to generate one automatically.")
	}

	hasSbom := false
	sbomCandidates := []string{sbomFileName, "sbom.spdx.json", "bom.json", "sbom/" + sbomFileName}
	for _, c := range sbomCandidates {
		if _, err := os.Stat(c); err == nil {
			hasSbom = true
			msg.Info("✅ SBOM (Software Bill of Materials): Found SBOM file at '%s'", c)
			break
		}
	}
	if !hasSbom {
		msg.Warn("❌ SBOM (Software Bill of Materials): Missing 'sbom.cdx.json'.")
		msg.Info("   -> To fix: Run 'boss sbom' or 'boss cra init' to generate it.")
	}

	// Validate boss.json exists
	if _, err := os.Stat("boss.json"); err != nil {
		msg.Warn("⚠️ boss.json: No boss.json found in current directory.")
	}

	if hasSecurity && hasSbom {
		msg.Info("\n🎉 Your local project is 100%% CRA compliant! Commit and push these files to GitHub to get the Gold badge in the portal.")
	} else {
		msg.Info("\n💡 Tips to get 100%% CRA badge:")
		msg.Info("1. Run 'boss cra init' to let Boss generate the SECURITY.md and SBOM automatically.")
		msg.Info("2. Commit and push the files to your repository.")
	}
}

// runCraInit runs the interactive wizard to generate compliance files.
func runCraInit() {
	msg.Info("🚀 Cyber Resilience Act (CRA) Compliance Wizard\n")

	// 1. Get security email
	email := securityEmail
	if email == "" {
		reader := bufio.NewReader(os.Stdin)
		fmt.Print("📧 Enter the email address to report security vulnerabilities: ")
		input, err := reader.ReadString('\n')
		if err != nil {
			msg.Die("❌ Failed to read email: %s", err)
		}
		email = strings.TrimSpace(input)
	}

	if email == "" {
		msg.Die("❌ An email address is required to generate the security policy.")
	}

	// 2. Generate SECURITY.md
	securityContent := fmt.Sprintf(`# Security Policy

## Reporting a Vulnerability

Please report security vulnerabilities directly to the maintainers at the following address:

📧 **%s**

Please do **NOT** open public issues or pull requests for security vulnerabilities until they have been reviewed and a fix is prepared. This keeps the report private and protects users of the package.

We aim to acknowledge reports within a few business days and keep you updated on progress.

## Supported Versions

Security fixes are applied to the latest active release. We recommend always running the latest version of this package.
`, email)

	// Never clobber a policy the project already has: it may be the real one.
	if _, err := os.Stat(securityPolicyFile); err == nil {
		msg.Warn("⚠️ '%s' already exists and was left untouched. Delete it first if you want Boss to regenerate it.", securityPolicyFile)
	} else if err := os.WriteFile(securityPolicyFile, []byte(securityContent), 0600); err != nil {
		msg.Die("❌ Failed to write %s: %s", securityPolicyFile, err)
	} else {
		msg.Info("✅ Created '%s' with your security contact details.", securityPolicyFile)
	}

	// 3. Generate the SBOM if boss.json is present
	if _, err := os.Stat("boss.json"); err == nil {
		msg.Info("📦 boss.json detected. Generating Software Bill of Materials (SBOM)...")

		data, err := os.ReadFile("boss.json")
		if err == nil {
			var manifest bossManifest
			_ = json.Unmarshal(data, &manifest)

			// Written as the canonical file name that runCraCheck looks for.
			// Naming it after the package would emit "<owner>/<name>.cdx.json",
			// which the compliance check cannot find -- and the slash in a
			// scoped package name is not even a valid file name.
			generateCycloneDxSbom(sbomBaseName, manifest, resolveSbomComponents(manifest), ".")

			if _, err := os.Stat(sbomFileName); err == nil {
				msg.Info("✅ Created '%s' in the project root.", sbomFileName)
			}
		}
	} else {
		msg.Warn("⚠️ No boss.json found. Skipping SBOM generation. Create a boss.json first.")
	}

	msg.Info("\n🎉 Compliance files generated successfully!")
	msg.Info("To get the 100%% CRA-ready badge in the PubPascal portal:")
	msg.Info("1. Commit the newly created 'SECURITY.md' and 'sbom.cdx.json' to Git.")
	msg.Info("2. Push them to your GitHub repository.")
}
