name: golangci-lint
on:
  push:
  pull_request:

permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
        env:
          ASDF_GOLANG_DEFAULT_PACKAGES_FILE: ./.default-golang-pkgs
      # - uses: actions/setup-go@v5
      #   with:
      #     go-version: "1.23.6"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.4'
      - uses: pre-commit/action@v3.0.1
