name: golangci-lint
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.4"
      - uses: pre-commit/action@v3.0.1
