name: boss-release

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up tooling
        uses: jdx/mise-action@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean --auto-snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          path: dist/boss_windows_amd64_v1/boss.exe
          if-no-files-found: warn

  build-setup:
    runs-on: windows-latest
    needs: goreleaser
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.6
        env:
          VERSION: ${{ github.ref }}
          BIN_DIR: dist/boss_windows_amd64_v1/boss.exe
        with:
          path: ./assets/installer/boss.iss
          options: /O+
